dora-team/dora.dev

- hugo/assets/js/results.js
- hugo/assets/js/results_2019.js
- hugo/assets/scss/main.scss
- hugo/assets/scss/quickcheck.scss
- hugo/assets/scss/quickcheck_2019.scss
- hugo/layouts/partials/quickcheck/prioritize.html
> 21-Make-the-help-me-prioritize-modal-responsive

- hugo/assets/scss/main.scss
- hugo/assets/scss/sidebar.scss
- hugo/layouts/partials/research_sidebar.html
> Fix sidebar on research section  (Fixes #89)

- hugo/content/research/archives/2014.md
- hugo/content/research/archives/2015.md
- hugo/content/research/archives/2016.md
- hugo/content/research/archives/2017.md
- hugo/content/research/archives/2018.md
- hugo/content/research/archives/2019.md
- hugo/content/research/archives/2020.md
- hugo/content/research/archives/2021.md
- hugo/content/research/archives/2022.md
- hugo/content/research/archives/_index.md
- hugo/data/survey_questions.json
- hugo/layouts/partials/research_sidebar.html
- hugo/layouts/research/section.html
- hugo/layouts/research/single.html
- hugo/layouts/research_archives/section.html
- hugo/layouts/research_archives/single.html
This PR adds research archive content for 2014-2019
> 93-Link-to-2019-report

- hugo/layouts/shortcodes/article.html
> Open offsite links on hp in new tab  (Fixes #114)

- hugo/assets/scss/forms.scss
> Fix button.secondary:hover style  (Fixes #70)

- firebase.json
> Add redirects from legacy urls  (Fixes #2)

- hugo/content/capabilities/architecture/index.md
- hugo/content/capabilities/cloud-infrastructure/index.md
- hugo/content/capabilities/code-maintainability/index.md
- hugo/content/capabilities/continuous-delivery/index.md
- hugo/content/capabilities/continuous-integration/index.md
- hugo/content/capabilities/database-change-management/index.md
- hugo/content/capabilities/deployment-automation/index.md
- hugo/content/capabilities/shifting-left-on-security/index.md
- hugo/content/capabilities/team-experimentation/index.md
- hugo/content/capabilities/teams-empowered-to-choose-tools/index.md
- hugo/content/capabilities/test-automation/index.md
- hugo/content/capabilities/test-data-management/index.md
- hugo/content/capabilities/transform/index.md
- hugo/content/capabilities/transformational-leadership/index.md
- hugo/content/capabilities/trunk-based-development/index.md
- hugo/content/capabilities/version-control/index.md
- hugo/content/capabilities/westrum-organizational-culture/index.md
Correct some typoes, fail links and formatting
> Capabilities fixes

- hugo/content/quickcheck/2019/results.html
Minor language adjust as agreed upon.
`We have created the URL to your DORA DevOps Quick Check below.
Copy and share via social media, email or chat.`
> Updated text for Issue #194

- hugo/layouts/research/single.html
- hugo/layouts/research_archives/single.html
> Fix sidebar on research archives  (Fixes #196)

- docs/README.md
√ Fixing Hugo ling in the setup. Read me. The previous was generating 404.
> Fixing hugo link in the setup readme

- hugo/content/resources/_index.md
> Update title for four keys section

- hugo/assets/scss/quickcheck_2019.scss
- hugo/content/quickcheck/2019/results.html
1) Added in .modal-close.x style back to quickcheck_2019.scss
2)Corrected misplacement of X in modal (results.html) that was missing style class ref. in HTML element
> Corrected style for Issue 214

- firebase.json
Added 301 redirects for 'prod' and 'draft' targets
> Updates for Issue 201 capabilities redirect

- hugo/assets/js/constants_2019.js
- hugo/content/devops-capabilities/cultural/generative-organizational-culture/index.md
- hugo/data/capability_prioritization_questions.json
`inquiry` can be interpreted many different ways.  We're really looking for being curious.
Fixes #218
> Clarify generative culture questions

- functions/inquiry-monitor/index.js
> add sender name to subject  (Fixes #227)

- hugo/config.toml
- hugo/static/robots.txt
Resolves issue #9 
A basic robots.txt with a sitemap pointer, and a sitemap for it to point to.
> Adds a robots.txt file and sitemap

- README.md
This PR adds a video from dora.community to the README of this repo
> Add video to README

- hugo/content/devops-capabilities/technical/test-automation/index.md
This PR changes the capability name "continuous testing" to "test automation" (to match the already-properly-named filename)
Fixes #237
> name change (Fixes #237)

- hugo/assets/scss/_variables.scss
- hugo/assets/scss/nav.scss
- hugo/content/survey/index.md
- hugo/layouts/partials/header.html
- hugo/layouts/partials/site_banner.html
- hugo/layouts/shortcodes/button.html
> add survey link

- hugo/content/devops-capabilities/process/customer-feedback/index.md
Hi, 
just correct a typo
Thanks
> fix typo in customer-feedback

- ci/preview-infra.cloudbuild.yaml
Adding a "patch" for two fold.  
1) Validate impact of approach and 
2) Test new container migrations
> 307 - Skipping SENT_TO updates for Staging environment

- hugo/layouts/partials/head.html
> Material icons broken  (Fixes #334)

- hugo/layouts/partials/site_banner.html
> Add Community Summit banner

- hugo/assets/scss/quickcheck.scss
- hugo/content/quickcheck/_index.md
This PR swaps the order of the first two questions on the quick check, to align with the order in which we prefer to present the four key SD metrics
> swap lead time and deploy freq

- hugo/assets/scss/grid.scss
- hugo/content/research/2022/dora-report/_index.md
Adds the localized versions of the 2022 report with links on the report's home page.
> 2022 localized

- hugo/content/research/2022/dora-report/_index.md
The Korean version of the 2022 report is now available, too.
> Adds Korean version of 2022 report

- hugo/content/research/2021/dora-report/_index.md
- hugo/content/research/2023/_index.md
This PR adds translated versions of the 2021 State of DevOps Report
Preview: https://doradotdev-staging--pr418-qio4nvao.web.app/research/2021/dora-report/
> add 2021 translations

- hugo/layouts/research_archives/section.html
The survey questions description includes a link to the report that summarizes the analysis about the questions.
https://doradotdev-staging--pr420-xz6hinax.web.app/research/2022/?tab_archives=questions
> Link to the report from the survey questions

- hugo/data/survey_questions.json
Also adds a description for Software Delivery Performance
https://doradotdev-staging--pr422-ks7f0th9.web.app/research/2022/?tab_archives=questions
Resolves #421
> add SD Perf options for 2022 questions

- firebase.json
- hugo/content/concepts/organizational-performance.md
- hugo/content/devops-capabilities/cultural/well-being/index.md
- hugo/content/research/_index.md
Changes from 'wellbeing' to 'well-being'
This change does not address #411 but does update the spelling everywhere else on the site.
https://doradotdev-staging--pr434-t9bee7nt.web.app/research/
https://doradotdev-staging--pr434-t9bee7nt.web.app/devops-capabilities/
https://doradotdev-staging--pr434-t9bee7nt.web.app/devops-capabilities/cultural/well-being/
> Correct the spelling of 'well-being'

- hugo/content/_index.md
* Links to the blog series
* Removes the link to last year's e-book
Fixes #301
> Link to the most recent DevOps Awards

- hugo/content/_index.md
> Fix Quick Check name on hompage

- hugo/data/survey_questions/2023.json
These questions offer different choices than Strongly Disagree >> Strongly Agree.
* Never
* Rarely
* Sometimes
* Often
* Always
* I don't know or NA
I didn't want to repeat those with every question and there's no way to list them as part of the explanatory sentence so I added them only after the last sentence.
Preview:  https://doradotdev-staging--pr469-3yqe14cm.web.app/research/2023/questions/#reliability
> Adds answer choices for r9y questions

- hugo/content/devops-capabilities/technical/test-automation/index.md
> Update broken link to an article on Wikipedia

- ci/preview-content.cloudbuild.yaml
> Replace Hugo builder with inline scripts  (Fixes #491)

- hugo/assets/js/results.js
- hugo/layouts/partials/quickcheck/prioritize.html
> Add conversion events for Quick Check  (Fixes #504)

- experimental/quick-check-2023/src/lib/MetricsQuestions.svelte
> Move "For the primary application..." text into each question text  (Fixes #519)

- ci/README.md
- hugo/content/quickcheck/2023/index.md
- svelte/quick-check-2023/src/App.svelte
- svelte/quick-check-2023/src/lib/Capability.svelte
- svelte/quick-check-2023/src/lib/HelpMePrioritize.svelte
- svelte/quick-check-2023/src/lib/MetricsQuestions.svelte
- svelte/quick-check-2023/src/lib/PerformanceGraph.svelte
- svelte/quick-check-2023/src/lib/PrioritizationResult.svelte
- svelte/quick-check-2023/src/lib/PrioritizationResults.svelte
- svelte/quick-check-2023/src/lib/YourPerformance.svelte
> 515-Make-quick-check-2023-responsive

- hugo/data/survey_questions/2018.json
`rathr` to `rather`
* Current state:  https://dora.dev/research/2018/questions/#working-in-small-batches
* Staged update:  https://doradotdev-staging--pr529-drafts-off-z9v1ugzq.web.app/research/2018/questions/#working-in-small-batches
> Fixes a misspelling in the 2018 questions

- hugo/content/_index.md
This PR adds a small bit of text on the homepage reflecting the updates to the quick check
> add "updated" text to quick check on homepage snipe

- hugo/content/research/2023/errata.md
This PR updates the errata page to add some previously-reported issues. (note that it doesn't add all of the reported issues; there are still some that need to be processed)
preview at
https://doradotdev-staging--pr539-drafts-on-sqwase11.web.app/research/2023/errata/
> addition of some errata

- ci/preview-infra.cloudbuild.yaml
- hugo/content/search/README.md
- hugo/content/search/_index.md
This PR adds an (unlinked) search page which embeds a search widget provided by Vertex AI Search and Conversation
> Create an interactive, search experience 

- hugo/content/_index.md
This PR simplifies the language at the top of the homepage.
> Simplify language on hp

- hugo/data/survey_questions/2023.json
Available for review here:  https://doradotdev-staging--pr547-drafts-off-ouc4846j.web.app/research/2023/questions/#artificial-intelligence
> Add group responses for the 2023 AI questions

- svelte/quick-check-2023/src/lib/MetricsQuestion.svelte
Previewable at https://doradotdev-staging--pr553-drafts-off-hor6cjmi.web.app/quickcheck
> Fix the failure recovery question text for the quick check

- hugo/content/quickcheck/_index.md
- hugo/content/quickcheck/kiosk/_index.md
- hugo/themes/dora/layouts/shortcodes/timestamp.html
- svelte/quick-check-2023/src/App.svelte
- svelte/quick-check-2023/src/lib/MetricsQuestion.svelte
This PR is WIP to add kiosk mode to the quick check.
It _should_ have no visible impact on the regular ("embedded") mode for the quick check.
> styles for kiosk mode

- hugo/content/research/team.md
> fix typo on team page

- hugo/content/survey/index.md
Updates `/survey` page to link to the survey.
Preview:  https://doradotdev-staging--pr572-drafts-on-rfmcyca0.web.app/survey
> 2024 Survey is live!

- test/redirects/redirects.csv
Validates proper redirects for:
* /devops-capabilities/cultural/how-to-empower-software-delivery-teams/
* /devops-capabilities/cultural/devops-culture-transform/
> Adds 2 new redirect tests

- ci/preview-content.cloudbuild.yaml
- test/playwright/.gitignore
- test/playwright/README.md
- test/playwright/package-lock.json
- test/playwright/package.json
- test/playwright/playwright.config.ts
- test/playwright/tests/homepage.spec.ts
This PR creates a basic framework for [Playwright](https://playwright.dev) tests and includes a simple smoke test (verify that the homepage includes the string "Get Better at Getting Better")
> add basic playwright tests

- test/playwright/README.md
> Initial set-up for Playwright tests

- hugo/content/sponsors/resource-center/index.md
attempting to fix some mobile rendering issues
> Try a shorter header

- svelte/quick-check-2023/src/lib/HelpMePrioritize.svelte
- svelte/quick-check-2023/src/lib/PrioritizationResult.svelte
- test/playwright/playwright.config.ts
- test/playwright/tests/quickcheck.spec.ts
This PR adds an E2E test for the quickcheck application.
> Add tests for quickcheck

- hugo/content/search/_index.md
This PR refines the display and behavior of the search results page. (The page remains in draft mode, so it will return a 404 on prod.)
Preview at:
https://doradotdev-staging--pr603-drafts-on-qgdus9aw.web.app/search/?q=small%20batches
_The search service itself (at search.dora.dev) is still very much WIP. But this PR's UI improvements are independent of the quality of results returned by the search microservice._
> refine UI of search page

- hugo/content/search/_index.md
Small continued progress -- still not exposed on prod
> Search WIP

- hugo/content/sponsors/resource-center/index.md
Preview here - https://doradotdev-staging--pr613-drafts-off-unc271sc.web.app/sponsors/resource-center/
> Adds DORA logos to the sponsor resource center

- test/playwright/tests/resources.spec.ts
> Add playwright tests for the resources page

- hugo/content/guides/dora-metrics-four-keys/index.md
Without this clarification, a reader might think of these as the four keys.
See also this [LinkedIn comment](https://www.linkedin.com/feed/update/urn:li:activity:7199756107869827072?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A7199756107869827072%2C7200742020032716800%29&dashCommentUrn=urn%3Ali%3Afsd_comment%3A%287200742020032716800%2Curn%3Ali%3Aactivity%3A7199756107869827072%29)
Preview:  https://doradotdev-staging--pr616-drafts-off-ycmnef3b.web.app/guides/dora-metrics-four-keys/
> Clarify the four keys as leading and lagging indicators

- hugo/content/guides/dora-metrics-four-keys/index.md
- test/playwright/tests/fourkeys-guide.spec.ts.bak
Preview:  https://doradotdev-staging--pr619-drafts-off-74z10gdf.web.app/guides/dora-metrics-four-keys/
> Four keys date update

- hugo/content/guides/dora-metrics-four-keys/index.md
* Add a `.` to the end of a sentence
* Updated the `updated` date
Preview:  https://doradotdev-staging--pr621-drafts-off-gchjknmd.web.app/guides/dora-metrics-four-keys/#next-steps
> minor typo fix

- hugo/data/survey_questions/2018.json
- hugo/data/survey_questions/2019.json
- hugo/data/survey_questions/2021.json
- hugo/data/survey_questions/2022.json
- hugo/data/survey_questions/2023.json
Fixes #185
Preview:
* https://doradotdev-staging--pr625-drafts-off-ndtk2z2r.web.app/research/2018/questions/#organizational-performance
* https://doradotdev-staging--pr625-drafts-off-ndtk2z2r.web.app/research/2019/questions/#organizational-performance
* https://doradotdev-staging--pr625-drafts-off-ndtk2z2r.web.app/research/2021/questions/#organizational-performance
* https://doradotdev-staging--pr625-drafts-off-ndtk2z2r.web.app/research/2022/questions/#organizational-performance
* https://doradotdev-staging--pr625-drafts-off-ndtk2z2r.web.app/research/2023/questions/#organizational-performance
> Add response options for organizational performance questions

- hugo/content/research/2022/dora-report/index.md
- test/playwright/tests/2022-report.spec.ts
* Adds 2022 blog posts
* Adds some playwright tests
Fixes #291
Preview:  https://doradotdev-staging--pr626-drafts-off-qkqjsu2h.web.app/research/2022/dora-report/
> Add blogs to 2022 report page

- hugo/content/research/2024/_index.md
- hugo/layouts/partials/research_archives.html
- test/playwright/.gitignore
- test/playwright/tests/2024-research.spec.ts
- test/playwright/tests/research.spec.ts
- test/playwright/tests/survey.spec.ts
Create a placeholder for the 2024 research
* Adds another call to take the survey
* Adds more playwright tests
New or updated pages:
* https://doradotdev-staging--pr635-drafts-off-ju8r636d.web.app/research/
* https://doradotdev-staging--pr635-drafts-off-ju8r636d.web.app/research/2024/
> Adds 2024 research page

- .gitignore
- hugo/content/guides/devops-culture-transform/index.md
- test/playwright/tests/guides/how-to-transform-guide.spec.ts
* Reorder the patterns
* Update the page title
* Update the updated date
* Adds simple playwright tests
Preview - https://doradotdev-staging--pr637-drafts-off-h28bdrs0.web.app/guides/devops-culture-transform/#:~:text=Additional%20analysis%20identified%20four%20patterns%20used%20by%20high%20performers%2C%20ordered%20by%20prevalence%3A
Fixes #628
> Reorder transformation patterns of high performers

- functions/inquiry-monitor/package-lock.json
- hugo/content/_index.md
Add a feature on the homepage promoting the new AI guide (and remove the ROI feature, for now anyway).
> add ai hp feature

- hugo/content/search/_index.md
- hugo/content/search/search.js
- hugo/layouts/partials/search_input.html
- hugo/layouts/search/section.html
- hugo/themes/dora/assets/scss/main.scss
- hugo/themes/dora/assets/scss/nav.scss
- hugo/themes/dora/assets/scss/search-input.scss
- hugo/themes/dora/assets/scss/search.scss
- hugo/themes/dora/layouts/partials/footer.html
- hugo/themes/dora/layouts/partials/header.html
- test/playwright/tests/search/search-page.spec.ts
This PR adds a search bar to the navigation, to expose the search UI previously deployed at dora.dev/search
> Search-in-nav

- svelte/core-v2/index.html
- svelte/core-v2/src/lib/Popover.svelte
- svelte/core-v2/src/lib/core_data.json
Adds descriptions for core v2 categories: Climate for learning, Fast flow, and Fast feedback
Fixes #654 
Preview: https://doradotdev-staging--pr655-drafts-off-num96shq.web.app/core-v2/
> 654 core v2 descriptions

- hugo/layouts/research/section.html
- svelte/core-v2/src/app.css
- svelte/core-v2/src/assets/_variables.css
- svelte/core-v2/src/lib/Arrow.svelte
- svelte/core-v2/src/lib/Column.svelte
- svelte/core-v2/src/lib/Entity.svelte
- svelte/core-v2/src/lib/EntityGroup.svelte
- svelte/core-v2/src/lib/Popover.svelte
- svelte/core-v2/src/lib/core_data.json
This PR updates many of the styles and layout for Core V2. It also updates the "preview" link beneath Core (on /research/) to point to /core-v2/
Preview at
https://doradotdev-staging--pr657-drafts-on-qnj7wbmb.web.app/core-v2/
Once this is merged, Core 2 will be _almost_ ready to launch. See #661 for details
> Styles etc. for Core 2

- hugo/content/concepts/measuring-and-improving.md
This is core v1.2.2
Preview: https://doradotdev-staging--pr669-drafts-off-hr2ac9nx.web.app/research
> Link to the four keys guide from the core model

- hugo/content/search/search.js
> Sanitize search input box  (Fixes #678)

- hugo/content/sponsors/resource-center/index.md
The survey is now closed, remove the information about running a campaign and other survey-related assets.
Preview - https://doradotdev-staging--pr690-drafts-off-tc7r7ww6.web.app/sponsors/resource-center/
Resolves issue #686
> Update sponsor resource center - the survey is now closed

- test/redirects/redirects.csv
> One more redirect for the 2014 report

- hugo/content/_index.md
- hugo/layouts/partials/site_banner.html
The submission deadline was July 31, 2024
Fixes #711 
Preview - https://doradotdev-staging--pr710-drafts-off-vvfdd1pt.web.app/
Expectation:
- no site banner
- no award CTA on the home page
> Remove DORA Award submissions

- hugo/content/publications/_index.md
- hugo/content/research/2018/dora-report/index.md
- test/playwright/tests/publications/index.spec.ts
This supports #698
Preview links:
* https://doradotdev-staging--pr715-drafts-off-xxq1cjep.web.app/publications/
* https://doradotdev-staging--pr715-drafts-off-xxq1cjep.web.app/research/2018/dora-report/
> Summarize the 2018 Report

- svelte/quick-check-2023/src/lib/YourPerformance.svelte
Fixes #531
Preview:
https://doradotdev-staging--pr713-drafts-off-dm2ccyln.web.app/quickcheck/?leadtime=5&deployfreq=4&changefailure=29&failurerecovery=4&v=2023&industry=all
> Display Quick Check legend vertically

- hugo/content/publications/_index.md
- hugo/content/research/2019/dora-report/index.md
- test/playwright/tests/publications/index.spec.ts
Updates `/publications` and `/research/2019/dora-report/` also updates the tests.
Preview links:
* https://doradotdev-staging--pr716-drafts-off-njca0ha7.web.app/publications/
* https://doradotdev-staging--pr716-drafts-off-njca0ha7.web.app/research/2019/dora-report/
> Summarize 2019 report

- hugo/assets/scss/capabilities.scss
Fixes #712
Preview - https://doradotdev-staging--pr719-drafts-off-2g6hogmc.web.app/capabilities/monitoring-and-observability/#whitebox-monitoring
> Adjust the size of code blocks in capabilities articles

- hugo/content/_index.md
Preview - https://doradotdev-staging--pr722-drafts-off-q7fwqoxv.web.app/
> Add AI Preview to the home page

- hugo/content/research/2024/ai-preview/index.md
resolves the typo flagged on the [community mailing list](https://groups.google.com/g/dora-community/c/58V_yf9N4CI/m/CSWI-0SpAAAJ?utm_medium=email&utm_source=footer)
> remove duplicate 'code explanation'

- hugo/content/capabilities/continuous-delivery/index.md
- Fixes page references
- Links directly to the referenced pages
- Adds a link to the 2021 report
Preview - https://doradotdev-staging--pr725-drafts-off-tsrt29yq.web.app/capabilities/continuous-delivery/
> Updates links to reports in CD capability

- hugo/content/capabilities/transformational-leadership/index.md
trivial fix.
preview - https://doradotdev-staging--pr726-drafts-off-fenax3fw.web.app/capabilities/transformational-leadership/
Expect `pp. 12-19` instead of `pp12-19`
> Fix a minor typo

- hugo/content/capabilities/generative-organizational-culture/index.md
Updating to help clarify the meaning for global readers who might not be familiar with the "don't shoot the messenger" metaphor.
See also b/235579359
Preview - https://doradotdev-staging--pr727-drafts-off-17lrdk7p.web.app/capabilities/generative-organizational-culture/
> Use less figurative language in the Westrum table

- hugo/content/faq/_index.md
Preview link:  https://doradotdev-staging--pr728-drafts-off-gfgxt32f.web.app//faq/#research-and-data
> Add an FAQ about data sharing

- firebase.json
- test/redirects/redirects.csv
Preview url:  https://staging.dora.dev/devops-capabilities/process/loosely-coupled-architecture/
> Add redirect for `/capabilities/loosely-coupled-architecture`

- hugo/assets/scss/research.scss
- hugo/content/research/2024/ai-preview/index.md
- hugo/layouts/research_archives/preview/single.html
- test/playwright/tests/research/2024/2024-ai-preview.spec.ts
Updates following editorial review
Also adds "Last updated" date to the page.
Preview:  https://doradotdev-staging--pr733-drafts-off-59z4xql1.web.app/research/2024/ai-preview/
> AI preview updates

- ci/README.md
- docs/README.md
- docs/developer-onboarding-guide.md
- docs/publishing-content.md
Adds new onboarding guide (thanks, Gemini!)
> Update developer documentation

- docs/developer-onboarding-guide.md
Thanks @nathenharvey for making the onboarding guide! This PR contains a handful of small edits.
> Various tweaks to onboarding guide

- hugo/content/contact/_index.md
The `.` should not be part of the link.
Preview:  https://doradotdev-staging--pr742-drafts-off-p5hlbrkg.web.app/contact/
> End sentences with a `.`

- hugo/content/guides/dora-metrics-four-keys/index.md
favor "efficient" over "agile".
Preview:  https://doradotdev--pr757-drafts-on-go0p4x87.web.app/guides/dora-metrics-four-keys/
> Minor edit to four keys

- hugo/content/research/2024/trust-in-ai/index.md
This sets `draft` to `false`
Preview :  https://doradotdev--pr764-drafts-off-z80g92a0.web.app/research/2024/trust-in-ai/
> Turn on the AI trust article

- hugo/content/research/2024/_index.md
* Adds a link to the trust in AI article
* Updates the link to the AI preview
Preview - https://doradotdev--pr768-drafts-off-7odh9420.web.app/research/2024/
> Link to the AI previews from 2024 research

- hugo/content/research/2024/trust-in-ai/index.md
This was broken by the previous commit
Preview - https://doradotdev--pr770-drafts-off-o8izrwcc.web.app/research/2024/trust-in-ai/
> Fix an in-page link

- hugo/content/_index.md
Preview - https://doradotdev--pr777-drafts-off-kxd367ot.web.app/
> AI trust on home page

- hugo/content/research/2023/dora-report/index.md
- test/playwright/tests/research/2023/2023-dora-report.spec.ts
In preparation for releasing the 2024 report.
Preview:
* https://doradotdev--pr784-drafts-off-trg0pa9w.web.app/research/2023/dora-report/
> Adds the 2023 report to dora.dev

- hugo/layouts/research_archives/questions/single.html
- test/playwright/tests/research/2024/2024-questions.spec.ts
Preview:
* https://doradotdev--pr790-drafts-off-3zvzf17d.web.app/research/2024/questions/
* https://doradotdev--pr790-drafts-off-3zvzf17d.web.app/research/2023/questions/
> Don't link to 2024 report before it's live

- hugo/content/vc/_index.md
Some 2023 report versions were listed as 2024
Preview:
* https://doradotdev--pr789-drafts-off-v2ionmbs.web.app/vc/
> Fix typo in version checker

- docs/adrs/003-use-alpineJS-for-light-weight-JS-framework.md
- docs/adrs/008-use-svelte-for-embedded-spas
> adr for svelte SPAs

- hugo/content/research/2024/dora-report/index.md
> Add a download button for the 2024 report

- hugo/content/decade/_index.md
- hugo/content/research/2024/_index.md
Use these instead of the png
Font issue has been resolved
Fixes #800
Preview:
* https://doradotdev--pr803-drafts-off-wu9pzxks.web.app/decade/
* https://doradotdev--pr803-drafts-off-wu9pzxks.web.app/research/2024/
> Updated infographic svg files

- hugo/content/research/2024/errata.md
- test/playwright/tests/research/2024/2024-errata.spec.ts
Preview - https://doradotdev--pr804-drafts-off-jb4210ve.web.app/research/2024/errata/
> First round of errata for 2024.1

- hugo/content/research/2024/errata.md
Preview: https://doradotdev--pr806-drafts-off-xlv86yhi.web.app/research/2024/errata/
> Errata for Figure 18

- hugo/content/vc/_index.md
Preview URLs:
* https://doradotdev--pr807-drafts-off-bh7o12dc.web.app/vc/?v=2023-10
* https://doradotdev--pr807-drafts-off-bh7o12dc.web.app/vc/?v=2023-12
* https://doradotdev--pr807-drafts-off-bh7o12dc.web.app/vc/?v=2024.1
> Link to errata if we have it

- hugo/content/research/2024/errata.md
- hugo/content/vc/_index.md
- test/playwright/tests/vc/version-check.spec.ts
Preview links:
* https://doradotdev--pr808-drafts-off-oxjcibli.web.app/research/2024/errata/
* http://doradotdev--pr808-drafts-off-oxjcibli.web.app/vc/
* http://doradotdev--pr808-drafts-off-oxjcibli.web.app/vc/?v=2024.2
* http://doradotdev--pr808-drafts-off-oxjcibli.web.app/vc/?v=2024.1
* http://doradotdev--pr808-drafts-off-oxjcibli.web.app/vc/?v=2023-12
* http://doradotdev--pr808-drafts-off-oxjcibli.web.app/vc/?v=2023-10
* http://doradotdev--pr808-drafts-off-oxjcibli.web.app/vc/?v=
* http://doradotdev--pr808-drafts-off-oxjcibli.web.app/vc/
* http://doradotdev--pr808-drafts-off-oxjcibli.web.app/vc/?v=216
* http://doradotdev--pr808-drafts-off-oxjcibli.web.app/vc/?v=1564-1586
* http://doradotdev--pr808-drafts-off-oxjcibli.web.app/vc/?v=783.3
* …
> Updates for v. 2024.2 of the report

- test/playwright/tests/vc/version-check.spec.ts
Refactor version checker tests to use data-version attributes for more robust and maintainable selectors. This approach decouples the tests from the visual presentation of the page and makes them less prone to breaking with HTML structure changes.
The isFirst property is removed from the versions array as it's no longer needed with the new selectors. Assertions are also simplified to focus on the presence or absence of the target element.
> Test: Improve version checker tests with data attributes

- hugo/content/faq/_index.md
* links to 2024 questions
* links to errata for 2023 and 2024
* links to the version checker for 2023 and 2024
* clarifies some of the questions about 2022
* expands the answer about performance clusters from 2022
Preview links:
- https://doradotdev--pr811-drafts-off-yuon8ls4.web.app/faq/
> Update the FAQ for 2024

- hugo/content/research/2024/dora-report/index.md
- hugo/layouts/partials/site_banner.html
- hugo/themes/dora/assets/scss/_variables.scss
- hugo/themes/dora/assets/scss/nav.scss
- hugo/themes/dora/layouts/partials/header.html
Adds the site banner.
Begins the work of introducing the 2024 colors.
Preview:
* https://doradotdev--pr814-drafts-off-lqznbkez.web.app/ (should have banner)
* https://doradotdev--pr814-drafts-off-lqznbkez.web.app/research/2024/dora-report (should not have banner)
> 2024 report banner

- hugo/content/decade/_index.md
- hugo/content/research/2024/_index.md
Hoping to prevent these getting out of sync with cgc
Preview links:
* https://doradotdev--pr815-drafts-off-oalawa5p.web.app/research/2024/
* https://doradotdev--pr815-drafts-off-oalawa5p.web.app/decade/
Should not notice any differences relative to production.
> Add two comments about infographics

- hugo/content/research/2024/errata.md
there's a lot
Preview - https://doradotdev--pr817-drafts-off-326c8vgz.web.app/research/2024/errata/
> Errata for v. 2024.2

- svelte/quick-check-2023/src/lib/data/metrics_question_responses.json
Fixes #819
Preview - https://doradotdev--pr823-drafts-off-cb2vv3e1.web.app/quickcheck
> Remove duplicate "day" from quickcheck response options

- hugo/content/research/2024/errata.md
- hugo/content/vc/_index.md
- test/playwright/tests/vc/version-check.spec.ts
Updates the errata for 2024.2
Preview - https://doradotdev--pr830-drafts-off-tydhf8ny.web.app/research/2024/errata/
Updates the version checker to reflect 2024.3
Preview links:
* https://doradotdev--pr830-drafts-off-tydhf8ny.web.app/vc?v=2024.3
* https://doradotdev--pr830-drafts-off-tydhf8ny.web.app/vc?v=2024.2
* https://doradotdev--pr830-drafts-off-tydhf8ny.web.app/vc?v=2024.1
> Report v 2024.3

- hugo/content/research/2021/dora-report/index.md
- hugo/content/research/2022/dora-report/index.md
Summarizes the 2021 and 2022 reports, finishing all of the outstanding summaries.
This fixes #698 
Preview links:
* https://doradotdev--pr833-drafts-off-axscan6p.web.app/research/2021/dora-report/
* https://doradotdev--pr833-drafts-off-axscan6p.web.app/research/2022/dora-report/
> Summarize more reports

- hugo/content/research/2024/errata.md
There are a few errors in the models diagram on page 116.
Preview:
https://doradotdev--pr836-drafts-off-9p1fn3o0.web.app/research/2024/errata/#errata-in-v20243
> Adds errata for v. 2024.3

- hugo/content/capabilities/code-maintainability/index.md
- hugo/content/capabilities/continuous-delivery/index.md
- hugo/content/capabilities/customer-feedback/index.md
- hugo/content/capabilities/database-change-management/index.md
- hugo/content/capabilities/generative-organizational-culture/index.md
- hugo/content/capabilities/job-satisfaction/index.md
- hugo/content/capabilities/learning-culture/index.md
- hugo/content/capabilities/loosely-coupled-teams/index.md
- hugo/content/capabilities/monitoring-and-observability/index.md
- hugo/content/capabilities/pervasive-security/index.md
- hugo/content/capabilities/proactive-failure-notification/index.md
- hugo/content/capabilities/streamlining-change-approval/index.md
- hugo/content/capabilities/team-experimentation/index.md
- hugo/content/capabilities/teams-empowered-to-choose-tools/index.md
- hugo/content/capabilities/test-data-management/index.md
- hugo/content/capabilities/transformational-leadership/index.md
- hugo/content/capabilities/trunk-based-development/index.md
Stop spelling out the acronymn's former meaning
Preview links:
* https://doradotdev--pr839-drafts-off-zhmgwx4c.web.app/capabilities/code-maintainability/
* https://doradotdev--pr839-drafts-off-zhmgwx4c.web.app/capabilities/continuous-delivery/
* https://doradotdev--pr839-drafts-off-zhmgwx4c.web.app/capabilities/customer-feedback/
* https://doradotdev--pr839-drafts-off-zhmgwx4c.web.app/capabilities/database-change-management/
* https://doradotdev--pr839-drafts-off-zhmgwx4c.web.app/capabilities/generative-organizational-culture/
* https://doradotdev--pr839-drafts-off-zhmgwx4c.web.app/capabilities/job-satisfaction/
* https://doradotdev--pr839-drafts-off-zhmgwx4c.web.app/capabilities/learning-culture/
* https://doradotdev--pr839-drafts-off-zhmgwx4c.web.app/capabilities/loosely-coupled-teams/ …
> Deacronymn DORA

- hugo/content/_index.md
Preview link - https://doradotdev--pr843-drafts-off-brtt48hx.web.app/
> Add Value of Dev Work article to home page

- hugo/themes/dora/layouts/partials/footer.html
Fixes #855, a sub-issue for #835
Preview link - https://doradotdev--pr857-drafts-off-4qqp3pba.web.app/
> Remove 'follow us on twitter' from the footer

- hugo/content/research/2024/errata.md
Preview URL: https://doradotdev--pr874-drafts-off-75d1mm0c.web.app/research/2024/errata/#errata-in-v20243
> Errata for the description of Figure 9 in the 2024 report.

- docs/developer-onboarding-guide.md
* Remove information about the contact form which has been deprecated
* Mark the Firebase CLI as optional
> Updates to the developer onboarding guide

- hugo/content/_index.md
- hugo/content/merch/_index.md
- test/playwright/tests/homepage.spec.ts
- test/playwright/tests/merch/merch.spec.ts
* Removes the feature from the home page
* Remove links to the order forms
* Update messaging on the page
* Update tests
Preview URLs
- https://doradotdev--pr888-drafts-off-r1ktjx1j.web.app/
- https://doradotdev--pr888-drafts-off-r1ktjx1j.web.app/merch/
> T-shirt sales have ended

- hugo/content/capabilities/documentation-quality/index.md
The percentages represent the lift to organizational performance as technical capabilities are implemented.
Preview URL: https://doradotdev--pr892-drafts-off-1cf2nbri.web.app/capabilities/documentation-quality/#lift-to-organizational-performance-as-technical-capabilities-are-implemented
> Clarify the contents of the doc quality table

- hugo/content/research/ai/value-of-development-work/index.md
Change case to better follow our style guide
* Sentence case for:
* headers
* gen AI
* the values (for example, Utilitarian value)
Preview: https://doradotdev--pr897-drafts-off-qq9671qi.web.app/research/ai/value-of-development-work/
> Update AI article about valuable work

- hugo/content/vc/_index.md
- hugo/content/vc/genai/index.md
- hugo/static/js/version-check-utils.js
- test/playwright/tests/vc/genai-version-check.spec.ts
Resolves #862
Preview URLs:
* https://doradotdev--pr898-drafts-off-m44rwj7k.web.app/vc/genai/?v=2025.1 - the current version
* https://doradotdev--pr898-drafts-off-m44rwj7k.web.app/vc/genai/?v=2024.1 - a non-existent version
* https://doradotdev--pr898-drafts-off-m44rwj7k.web.app/vc/genai/?v= - no version specified
> Add version tracker for gen AI guide

- hugo/content/research/ai/adopt-gen-ai/index.md
- hugo/content/research/ai/trust-in-ai/index.md
Editoral changes based on internal feedback and to align with the upcoming report on gen AI.
Preview URLs:
* https://doradotdev--pr918-drafts-off-lu43imte.web.app/research/ai/trust-in-ai/
* https://doradotdev--pr918-drafts-off-lu43imte.web.app/research/ai/adopt-gen-ai/
> Update two AI research articles

- hugo/content/research/ai/adopt-gen-ai/index.md
For the arcticle on adopting AI
Preview URL - https://doradotdev--pr919-drafts-off-ksr8lf1g.web.app/research/ai/adopt-gen-ai/#allow-ample-time-for-developers-to-learn-how-to-use-ai
> One additional editoral update

- hugo/content/sponsors/_index.md
Preview - https://doradotdev--pr962-drafts-off-9op2vmd7.web.app/sponsors/
Should show a Platinum sponsorship level and not show a Premiere level.
> Top teir 2025 sponsorship is called "Platinum"

- hugo/content/research/2024/dora-report/index.md
- test/playwright/tests/research/2024/2024-dora-report.spec.ts
Preview URL: https://doradotdev--pr988-drafts-off-9ymb1ym1.web.app/research/2024/dora-report/
> 2024 report is available in 10 languages

- hugo/content/research/2024/errata.md
Preview - https://doradotdev--pr992-drafts-off-nit479qi.web.app/research/2024/errata/
> Adds an errata for the model in v 2024.3

- hugo/data/survey_questions/core.json
Production: https://dora.dev/research/core/questions/#loosely-coupled-teams which reads "Think about how your team and work are structured. For the you work on, please rate how strongly"
"For the you work on" is missing "primary application or service"
Preview: https://doradotdev--pr998-drafts-off-rz5u0gpk.web.app/research/core/questions/#loosely-coupled-teams
> Fix omission in one of the core questions

- hugo/content/research/ai/_index.md
Remove the `heroimage` from the AI research landing page.
Preview: https://doradotdev--pr1008-drafts-off-11yn2aax.web.app/research/ai/
> Clean-up AI research section

- hugo/content/research/2024/dora-report/index.md
- test/playwright/tests/research/2024/2024-dora-report.spec.ts
Preview URL: https://doradotdev--pr1009-drafts-off-28fjz1xm.web.app/research/2024/dora-report/
> There is no Italiano version of the 2024 report.

- hugo/content/survey/_index.md
- hugo/content/survey/discussion-guide/index.md
Update the survey page and discussion guide to clarify that it takes about 15 minutes, not about 10 minutes, to complete the survey.
Preview:
* https://doradotdev--pr1020-drafts-off-s03da204.web.app/survey/
* https://doradotdev--pr1020-drafts-off-s03da204.web.app/survey/discussion-guide/
> The 2025 survey takes about 15 minutes

- hugo/content/survey/_index.md
- hugo/content/survey/discussion-guide/index.md
* Update one of the questions in the survey disucssion guide to avoid the phrase "elite performance".
* Update the list of benefits teams will get by taking the survey
* /survey/
* /survey/discussion-guide/
Preview:
* https://doradotdev--pr1021-drafts-off-k1mtblrd.web.app/survey/
* https://doradotdev--pr1021-drafts-off-k1mtblrd.web.app/survey/discussion-guide/
> Don't talk about 'elite performance'

- hugo/content/research/2024/dora-report/index.md
The `type` was declared twice, remove one of them.
Preview: https://doradotdev--pr1030-drafts-off-arcdthlr.web.app/research/2024/dora-report/
> Remove duplicate front-matter

- hugo/content/research/2014/_index.md
- hugo/content/research/2015/_index.md
- hugo/content/research/2016/_index.md
- hugo/content/research/2017/_index.md
- hugo/content/research/2018/dora-report/index.md
- hugo/content/research/2019/dora-report/index.md
- hugo/content/research/2020/_index.md
- test/playwright/tests/research/2016/2016.spec.ts
- test/playwright/tests/research/2017/2017.spec.ts
- test/playwright/tests/research/2020/2020-research.spec.ts
fixes #994
Preview URLs:
* https://doradotdev--pr1028-drafts-off-yr84pg7a.web.app/research/2014/
* https://doradotdev--pr1028-drafts-off-yr84pg7a.web.app/research/2015/
* https://doradotdev--pr1028-drafts-off-yr84pg7a.web.app/research/2016/
* https://doradotdev--pr1028-drafts-off-yr84pg7a.web.app/research/2017/
* https://doradotdev--pr1028-drafts-off-yr84pg7a.web.app/research/2018/dora-report/
* https://doradotdev--pr1028-drafts-off-yr84pg7a.web.app/research/2019/dora-report/
* https://doradotdev--pr1028-drafts-off-yr84pg7a.web.app/research/2020/
> Refactor: Change report download links to buttons

- hugo/content/research/2021/dora-report/index.md
- hugo/content/research/2022/dora-report/index.md
- hugo/content/research/2023/dora-report/index.md
- hugo/content/research/2024/dora-report/index.md
- test/playwright/tests/research/2021/2021-dora-report.spec.ts
- test/playwright/tests/research/2022/2022-dora-report.spec.ts
- test/playwright/tests/research/2023/2023-dora-report.spec.ts
- test/playwright/tests/research/2024/2024-dora-report.spec.ts
Use buttons instead of a list of links for downloading reports in various languages.
Preview URLs:
* https://doradotdev--pr1032-drafts-off-08uy0m2y.web.app/research/2024/dora-report/
* https://doradotdev--pr1032-drafts-off-08uy0m2y.web.app/research/2023/dora-report/
* https://doradotdev--pr1032-drafts-off-08uy0m2y.web.app/research/2022/dora-report/
* https://doradotdev--pr1032-drafts-off-08uy0m2y.web.app/research/2021/dora-report/
> Language links to buttons

- hugo/content/capabilities/working-in-small-batches/index.md
* Add relevant publications
* Remove inline link to 2016 report
Preview URL: https://doradotdev--pr1037-drafts-off-raapv4pm.web.app/capabilities/working-in-small-batches/
> Update Working in small batches

- hugo/content/capabilities/test-automation/index.md
- test/playwright/tests/capabilities/test-automation.spec.ts
Updates:
* Add updated date
* Style change, '*' for bullets
* Added new characteristics of automated testing in the "How to implement automated testing" section.
* Update link to TDD book, the second edition is available
* Update link to Succeeding with Agile
* Remove link to Google Cloud DevOps page
* Update names and links for
* Google Cloud Build
* Google Cloud's Observability suite
* Add More from DORA section
Adds playwright test
Preview: https://doradotdev--pr1043-drafts-off-dg6rb2u3.web.app/capabilities/test-automation/
> Update the Test Automation capability

- hugo/content/_index.md
- hugo/content/awards/_index.md
Preview: 
* https://doradotdev--pr1067-drafts-off-t9uuaadc.web.app/ - home page feature updated
* https://doradotdev--pr1067-drafts-off-t9uuaadc.web.app/awards/#2025-google-cloud-dora-awards-ceremony
> Add 2025 Google Cloud DORA Awards ceremony recording

- hugo/content/research/shared/measurement-frameworks/index.md
Preview URLs:
* https://doradotdev--pr1078-drafts-off-j41et4um.web.app/research/2025/measurement-frameworks/#step-1-decide-on-why
* https://doradotdev--pr1078-drafts-off-j41et4um.web.app/research/2025/measurement-frameworks/#step-2-decide-on-what-and-how
> Add two additional headers to the measurement frameworks article

- hugo/content/research/2024/questions.md
- hugo/data/survey_questions/2024.json
It was noticed and captured in issue #837  that the question answers from the 2024 survey were in an unexpected order. This PR address it.
Preview URL: https://doradotdev--pr1079-drafts-off-pe47d080.web.app/research/2024/questions/
Fixes #837
> Adjusting all "I don't know" or "I don't know or NA" responses to the end of each question, where applicable.

- hugo/content/research/2025/_index.md
Preview URL: https://doradotdev--pr1080-drafts-off-ajn8xu5n.web.app/research/2025/#get-a-head-start
> Add measurement article to 2025 research home page

- hugo/content/research/2025/errata/index.md
Preview: https://doradotdev--pr1108-drafts-off-6eltby0e.web.app/research/2025/errata/
> Add errata for Methodology chapter

- hugo/content/research/2025/errata/index.md
Moths don't deploy. But it sometimes takes months.
Preview - https://doradotdev--pr1111-drafts-off-qwjqvsxu.web.app/research/2025/errata/
> Errata for Figure 12

- hugo/content/faq/_index.md
- hugo/themes/dora-2025/layouts/faq/section.html
Preview: https://doradotdev--pr1116-drafts-off-qtjoz6t5.web.app/faq/
Adds FAQs for
* State of AI-assisted Software Development
* Impact of Generative AI in Software Development
Adds the "Last updated" date for the FAQs page.
Fixes #1115
> Add FAQ entries for 2025 report
