hugo/assets/scss/publications.scss

This PR makes the publications page responsive (by switching the grid layout to have only one column)
fixes #97

responsive styles for `/publications` (fixes #97)

---

hugo/content/research/archives/2021.md

The [2021 research archive](https://dora.dev/research/archives/2021/) now links to the 2021 report instead of a 404.

Fix link to 2021 report

---

hugo/assets/scss/nav.scss
hugo/layouts/partials/head.html
hugo/layouts/partials/header.html

This PR: 
- adds "open in new tab" icons to the Capabilities and Community links in the top menu.
- _For "Capabilities", this is a temporary addition; that content will be migrated onto dora.dev shortly_
- adds indication of which page the user is currently on
Fixes #106 
Fixes #100

add page indicator to nav  (Fixes #100)

---

hugo/assets/scss/main.scss

The base font size was 0.85rem, for no apparent reason... that's awful small. This PR increases it to 1em.

increase base font size

---

hugo/assets/scss/devops-capabilities.scss

This PR makes the index of the capabilities page (/devops-capabilities/) responsive, by reducing to two columns on medium-width screens, and one column on narrow screens.
Fixes #165

Make capabilities index responsive  (Fixes #165)

---

adrs/use-alpineJS-for-light-weight-JS-framework.md
hugo/assets/js/results_2019.js
hugo/assets/scss/quickcheck_2019.scss
hugo/content/quickcheck/2019/results.html
hugo/layouts/quickcheck_2019/single.html

Limited changes to 2019 Quick Check functional areas, but could be leveraged in future patterns.
Foundational:  Added AlpineJS include in Main Layout template for 2019.  After full adoption of Alpine (if agreed via ADR), we should move into global level templates.
Functional changes:
**For _Share Results_ and _How was this calculated?_ helper popup**: Added functionality to close window upon: Escape or Enter keys and click outside.
**For "Help Me Prioritize**:    I did not close on Click outside because with the user already clicking various radio buttons, I did not want the user to "loose" their work upon an accidental click off modal.  However, I did add functionality to close window on "Escape" (a more deliberate action, in my opinon.

Close popovers on click outside or escape

---

hugo/content/research/_index.md
hugo/content/research/archives/2017.md
hugo/content/research/archives/2018.md
hugo/content/research/archives/2019.md
hugo/content/research/archives/2020.md
hugo/content/research/archives/2021.md
hugo/content/research/archives/2022.md

Comments in markdown files are kind of a non-thing, so we've been using [a hacky workaround](https://github.com/dora-team/dora.dev/blob/ccc4ea6b744b706dfbd3e28a4a396d4398b43056/hugo/content/research/archives/2018.md?plain=1#L12-L14). 
But TIL that in the _front matter_ of markdown files, we can use a simple `#` prefix to make comments. That feels like a reasonable compromise and makes the files nicer to look at; this PR adopts that format.

use proper comments in MD files

---

hugo/assets/js/constants_2019.js
hugo/content/quickcheck/2019/results.html
hugo/data/capability_prioritization_questions.json
hugo/layouts/partials/pagefooter_gofurther.html

updates capabilities links to be relative to the site, not linking to legacy.
Fixes #212

Fixes legacy links

---

hugo/assets/scss/publications.scss

This helps to resolve issue #142 
1. The grid reduces to two columns at the "large" breakpoint
2. The images are set to 100%, so they take up the available width at intermediate sizes
Max screens
Medium and large screens
Small screens

Make Publications responsive-er

---

hugo/content/devops-capabilities/cultural/generative-organizational-culture/index.md
hugo/content/devops-capabilities/cultural/job-satisfaction/index.md
hugo/content/devops-capabilities/cultural/learning-culture/index.md
hugo/content/devops-capabilities/cultural/transformational-leadership/index.md
hugo/content/devops-capabilities/process/customer-feedback/index.md
hugo/content/devops-capabilities/process/monitoring-systems/index.md
hugo/content/devops-capabilities/process/proactive-failure-notification/index.md
hugo/content/devops-capabilities/process/streamlining-change-approval/index.md
hugo/content/devops-capabilities/process/team-experimentation/index.md
hugo/content/devops-capabilities/process/visual-management/index.md
hugo/content/devops-capabilities/process/wip-limits/index.md
hugo/content/devops-capabilities/process/work-visibility-in-value-stream/index.md
hugo/content/devops-capabilities/process/working-in-small-batches/index.md
hugo/content/devops-capabilities/technical/cloud-infrastructure/index.md
hugo/content/devops-capabilities/technical/code-maintainability/index.md
hugo/content/devops-capabilities/technical/continuous-delivery/index.md
hugo/content/devops-capabilities/technical/continuous-integration/index.md
hugo/content/devops-capabilities/technical/database-change-management/index.md
hugo/content/devops-capabilities/technical/deployment-automation/index.md
hugo/content/devops-capabilities/technical/loosely-coupled-architecture/index.md
hugo/content/devops-capabilities/technical/monitoring-and-observability/index.md
hugo/content/devops-capabilities/technical/shifting-left-on-security/index.md
hugo/content/devops-capabilities/technical/teams-empowered-to-choose-tools/index.md
hugo/content/devops-capabilities/technical/test-automation/index.md
hugo/content/devops-capabilities/technical/test-data-management/index.md
hugo/content/devops-capabilities/technical/trunk-based-development/index.md
hugo/content/devops-capabilities/technical/version-control/index.md

This PR removes the boilerplate copy at the top of every capability article. (That copy is no longer necessary, as discussed in #167.)
Fixes #176

Remove boilerplate (Fixes #176)

---

hugo/content/survey/index.md
hugo/layouts/partials/site_banner.html

_DO NOT MERGE until the survey has closed!_
This PR removes the survey banner from all pages, and updates the content of `/survey`.
(Note that when we publish SODR 2023, we should update the stats on this page, but for now we can stick with the c. 2022 numbers)
Fixes #270

Remove survey CTAs  (Fixes #270)

---

ci/README.md
ci/preview-content.cloudbuild.yaml
docs/README.md
hugo/config.toml
hugo/content/devops-capabilities/_index.fr.md
hugo/content/devops-capabilities/technical/cloud-infrastructure/index.fr.md
hugo/layouts/devops-capabilities/section.html
hugo/layouts/devops-capabilities/single.html
hugo/layouts/partials/language_selector.html

This PR adds some config for adding French pages (I'm using French in development, but our i18n launch will include ~8 languages), and a dropdown menu to navigate between them.
None of this will be visible on the prod site; it only displays in "Draft" environments.
For the time being, anything other than the capability catalog (and Core) is out of scope for i18n, but we hope to translate the entire site, as quickly as we're able.

Initial i18n skaffolding

---

.firebaserc
firebase.json

Prod. updated and tested.
@davidstanke - This update PR just updates the extension version and deployment etags.  No impact since we are applying `firebase deploy --except=extensions ` - However, it will keep things in sync for future InfraAsCode efforts.
Ready for review

Updates to Extension Version + instance etages

---

.firebaserc
ci/cloudbuild.yaml
ci/preview-infra.cloudbuild.yaml
extensions/firestore-send-email.env.doradotdev
extensions/firestore-send-email.env.doradotdev-staging

Re-enabled Email extension to be managed as Infra as Code via `firebase deploy`
Upon PR Merge, this will impact production as `firebase deploy` is leveraged for production

Re-enable Extension Infra as Code

---

firebase.json

We've discovered there are additional links in the wild pointing to a different variant of the "DORA joins Google Cloud" link. This PR adds another redirect for that other url.

Add additional redirect for "DORA joins Google Cloud" page

---

hugo/content/_index.md

This PR replaces the homepage headline with "Get Better at Getting Better" -- a more emotive/call-to-action sort of thing. DORA has used this phrase in various contexts and it resonates with people.

change headline on homepage

---

hugo/layouts/contact/section.html

This PR adds <select> options to the contact us form allowing users to report errors in specific publications. Valid errors will (eventually) be published to the site, as per #375.
Fixes #378

Add "report an error" option to "Contact Us" form

---

firebase.json

Fixes #368
This PR:
- adds the 2022 report PDF (at URL `/research/2022/dora-report/2022-dora-accelerate-state-of-devops-report.pdf`)
- adds a convenience link: `dora.dev/dora-report`, which redirects to the page on cloud.google.com where users can download the latest report
- changes the redirect for `/core` to a 302 (just because I was in that file and there's no longer a reason for that to be a temporary redirect)

Add 2022 report  (Fixes #368)

---

hugo/content/publications/errata.md
hugo/layouts/contact/section.html

This PR adds a page at `/publications/errata/` -- per #375, it will eventually list all errata reported and addressed in DORA publications. At launch, it contains only a link to the form where users can report errors.
Preview it at:
https://doradotdev-staging--pr404-z5bkbgqc.web.app/publications/errata/
Fixes #403

Add stub errata page  (Fixes #403)

---

hugo/archetypes/devops-capabilities.md
hugo/assets/scss/headings.scss
hugo/content/devops-capabilities/cultural/how-to-empower-software-delivery-teams/index.md
hugo/layouts/devops-capabilities/single.html

This PR stages the "DORA for leadership" guide, under the Cultural DevOps Capabilities. (Similarly to "How to Transform," this is a slightly different kind of content than most of the capabilties. As a fast-follow, we plan to move such Guides into a new section. That will happen after State of DevOps 2023 is published.)
Note that because the front matter specifies `draft: true`, the article will only be visible on the draft server for now.
Fixes #405

"DORA for Execs" guide  (Fixes #405)

---

hugo/content/research/team.md

* Dustin Smith moves to the collective
* Add to the collective:
* Amanda Lewis
* James Brookbank
* Jeffrey P. Winer, PhD
* Kevin Storer
* Steve McGhee
Recognize PhDs for Daniella Villalba and Nicole Forsgren

Updates the research team for 2023

---

firebase.json

This PR adds a shortlink: `/report` which redirects to the latest State of DevOps Report. Preview at https://staging.dora.dev/report
After this is merged and deployed, we can send users to `dora.dev/report` to download the newest report.

add /report shortlink

---

hugo/layouts/research_archives/questions/single.html

This PR adds `id` elements to headings on the Survey Question pages within `/research/<year>` sections.
By adding `id`s, anchor links will automatically be appended, by the script /hugo/themes/dora/layouts/partials/heading_anchor_links.html
Preview example:
https://doradotdev-staging--pr454-draft-b6a7pjiv.web.app/research/2023/questions/#burnout
Fixes #452

add ids to survey question headings

---

hugo/content/faq/_index.md

This PR adds an item to the FAQ with instructions on how to submit a correction to SODR 2023
Preview:
https://doradotdev-staging--pr455-draft-f2ln1grb.web.app/faq/#accelerate-state-of-devops-report-2023

add 2023 errata link to faq

---

hugo/content/devops-capabilities/technical/continuous-integration/index.md

The capability article on CI links the phrase "An agreement that when the build breaks, fixing it should take priority over any other work." to the TBD article. However, that concept is actually described in the CD article. This PR fixes that.

fix "take precedence over other work" link

---

hugo/content/publications/_index.md

This PR updates the URLs linked from the thumbnails and titles on the `/publications` page, to match the destination on the "download the report" CTAs.
Preview: https://doradotdev-staging--pr464-draft-wlp2rp9a.web.app/publications/
Fixes #457

update thumbnail and title urls

---

hugo/data/survey_questions/2023.json

adds the missing question about knowledge sharing:  Knowledge silos prevent me from getting ideas across the organization
Preview fix:  https://doradotdev-staging--pr466-2fgml8kl.web.app/research/2023/questions/#knowledge-sharing
fixes #465

fix:  knowledge sharing questions

---

hugo/content/research/team.md

Adds PhD to Kevin's listing on the research collective page
Preview here:  https://doradotdev-staging--pr468-zybrf6iy.web.app/research/team/#meet-the-dora-collective
fixes #467

fix: Kevin Storer's credentials

---

hugo/config.toml
hugo/themes/dora/layouts/partials/head.html

This sets up the RSS capability.
We can create a custom RSS template if needed. This uses Hugo's default.
The feed is added at `/index.xml` and there's a reference to this in the HTML head of the site, to help with discoverability.
See #433

Adds RSS capability using default Hugo template

---

hugo/content/devops-capabilities/cultural/devops-culture-transform/index.md
hugo/content/devops-capabilities/cultural/generative-organizational-culture/index.md
hugo/content/devops-capabilities/technical/continuous-delivery/index.md

The site has been taken down so this updates links to new targets.

Remove links to rework.withgoogle.com

---

hugo/assets/scss/quickcheck_2019.scss
hugo/content/quickcheck/2019/results.html

A side effect of #451 caused improper alignment on results from the 2019 quick check (see #474). This PR fixes the alignment by changing `<h3>` elements to `<p>` elements. It also adds `target="_blank"` so the links to capability articles will open in new tabs.
Preview:
https://doradotdev-staging--pr476-draft-gamkzldy.web.app//quickcheck/2019/results/?leadtime=5&deployfreq=4&chgfail=6&ttr=6&industry=government
Fixes #474

fix quickcheck 2019 alignment

---

hugo/content/devops-capabilities/technical/loosely-coupled-architecture/index.md

While reading the page that describes the [Loosely coupled architecture](https://dora.dev/devops-capabilities/technical/loosely-coupled-architecture/) capability, I noticed an out of place `{` under the "Case study: Datastore" section. 
I think that the author meant to mention "Datastore service" there, but I'm not entirely sure.

Fix mention of the Datastore service on the "Loosely coupled architecture" page

---

hugo/layouts/devops-capabilities/section.html

This PR adds `id` attributes to the `<h2>` tags on the Capabilities index, so that they will automatically reveal anchor URLs on hover.
https://doradotdev-staging--pr484-draft-e41wym63.web.app/devops-capabilities/#technical

add heading link to capabilities index

---

hugo/content/_index.md
hugo/content/concepts/organizational-performance.md
hugo/content/publications/_index.md
hugo/content/research/2020/_index.md
hugo/layouts/partials/pagefooter_gofurther.html

Temporarily remvove from the site while we decide how to proceed
This removes links to the ROI report which has been removed for cloud.google.com
This should be reverted when the report is available again

The ROI report is no longer availalbe

---

hugo/content/_index.md
hugo/content/concepts/organizational-performance.md
hugo/content/publications/_index.md
hugo/content/research/2020/_index.md
hugo/layouts/partials/pagefooter_gofurther.html

This reverts commit fda777dadfd743ad1869bbf1ba35c5de0a018355.
* https://doradotdev-staging--pr489-hllrdvda.web.app/
* No DevOps Dozen Award
* Includes link to ROI report
* https://doradotdev-staging--pr489-hllrdvda.web.app/research
* Organizational Performance modal includes link to ROI report
* https://doradotdev-staging--pr489-hllrdvda.web.app/publications
* Includes link to ROI report
* Header, "Additional Publications", is plural
* https://doradotdev-staging--pr489-hllrdvda.web.app/research/2020
* Includes a link to the report
* https://doradotdev-staging--pr489-hllrdvda.web.app/quickcheck
* Results page includes a link to the report in the footer

Revert "The ROI report is no longer availalbe"

---

hugo/themes/dora/layouts/partials/footer.html

This PR changes the destination of the YouTube icon in the footer from the old (now deprecated) playlist to the new DORA YouTube channel.

Update footer link to new DORA YouTube channel

---

hugo/data/survey_questions/2023.json

The 2023 survey asked about job satisfaction but the phrasing of the question did not lend itself to a scale from 'strongly disagree' to 'strongly agree,'
This adds the response options:
* Extremely satisfied
* Satisfied
* Slightly satisfied
* Neither satisfied nor dissatisfied
* Slightly dissatisfied
* Dissatisfied
* Extremely dissatisfied
* I don't know or prefer not to answer
Validate at https://doradotdev-staging--pr520-drafts-off-7mt6wy3a.web.app/research/2023/questions/#job-satisfaction
Compare to https://dora.dev/research/2023/questions/#job-satisfaction

Add job satisfaction answer options

---

svelte/quick-check-2023/src/lib/MetricsQuestions.svelte

This PR replaces the `<dataList>` element (which doesn't seem to want to show up on Safari) with simpler block elements and styles. On my machine, it's working on Chrome and Safari.
Preview: https://doradotdev-staging--pr526-drafts-on-eixni5mz.web.app/quickcheck/2023
Fixes #525

Change Fail Rate tickmarks not appearing on Safari  (Fixes #525)

---

hugo/layouts/partials/site_banner.html

It's time to turn off the banner promoting the 2023 state of devops report.

remove 2023 report banner

---

firebase.json

This PR adds a redirect for a PDF related to the Accelerate book, which is hosted on IT Revolution's site, but for which the bitly link in Accelerate points to this site (via redirect from devops-research.com).
Preview here (it should redirect to the PDF on itrevolution.com): https://staging.dora.dev/assets/transformation_practices.pdf
Fixes #537

add redirect for transformation practices pdf

---

svelte/quick-check-2023/src/lib/YourPerformance.svelte

Fixes #541
Preview at: 
https://doradotdev-staging--pr543-drafts-on-3rr3gw40.web.app/quickcheck/?leadtime=2&deployfreq=6&changefailure=50&failurerecovery=3&step=results&v=2023&industry=all
-vs-
https://doradotdev-staging--pr543-drafts-on-3rr3gw40.web.app/quickcheck/?leadtime=2&deployfreq=6&changefailure=51&failurerecovery=3&step=results&v=2023&industry=all

Quick Check 2023: if a metric's value is an integer, omit the decimal component  (Fixes #541)

---

firebase.json
test/redirects/redirects.csv

This PR adds a redirect for the URL `/next24` -- we will provide this to attendees at the Google Cloud Next conference so they can take the State of DevOps Survey (which we expect will be live by that time). Until the destination link is live, however, it simply redirects to the `/survey` page
preview at: https://staging.dora.dev/next24

add /next24 redirect

---

firebase.json
test/redirects/redirects.csv

Preview links:
* http://staging.dora.dev/dora-report-2023
* http://staging.dora.dev/dora-report-2022
* http://staging.dora.dev/dora-report-2021
* http://staging.dora.dev/dora-report-2020
* http://staging.dora.dev/dora-report-2019
* http://staging.dora.dev/dora-report-2018
* http://staging.dora.dev/dora-report-2017
* http://staging.dora.dev/dora-report-2016
* http://staging.dora.dev/dora-report-2015
* http://staging.dora.dev/dora-report-2014

Redirect research archives

---

hugo/content/quickcheck/kiosk/_index.md
svelte/quick-check-2023/index.html
svelte/quick-check-2023/src/App.svelte
svelte/quick-check-2023/src/lib/FullScreen.svelte
svelte/quick-check-2023/src/lib/FullScreenButton.svelte
svelte/quick-check-2023/src/lib/MetricsQuestion.svelte

This PR adds styles (and some other bits) to enable kiosk mode for the quick check. It also takes the path `/quickcheck/kiosk` out of draft mode, so that will be live (though unlinked) on prod when this is merged. It's not quite done yet, but it's pretty close now.
Preview at:
https://doradotdev-staging--pr559-drafts-off-1nxaf54j.web.app/quickcheck/kiosk/
Default ("embedded") mode should be unchanged:
https://doradotdev-staging--pr559-drafts-off-1nxaf54j.web.app/quickcheck/
Note that the kiosk layout is specifically targeting a Pixel tablet and it may not be great at other sizes (it's not fully responsive).

More quick check styles / elements

---

hugo/content/guides/_index.md
hugo/content/guides/dora-metrics-four-keys/index.md
hugo/layouts/guides/single.html

This PR adds the Four Keys Guide at location `/guides/dora-metrics-four-keys/` -- this PR does _not_ update the site navigation or otherwise provide any links to the page.
TODO (in a future PR):
* replace the first two bullet points with a graphic ([or not?](https://github.com/dora-team/dora.dev/issues/558))
* Add an index page at `/guides/`
* Add guides to site nav
* move "how to transform" and "how to empower..." to the guides section
Preview at:
https://doradotdev-staging--pr562-drafts-on-75237c97.web.app/guides/dora-metrics-four-keys/

publish four keys guide (unlinked)

---

hugo/content/guides/dora-metrics-four-keys/index.md

This also fixes a broken link to /research
Preview and validate:  https://doradotdev-staging--pr566-drafts-off-lgk5b64h.web.app/guides/dora-metrics-four-keys/

Use relative links in the guide

---

svelte/quick-check-2023/src/App.svelte
svelte/quick-check-2023/src/lib/kiosk/StartOver.svelte

This PR adds a timer to the `StartOver` component which automatically resets the application if it is idle for 90 seconds. For the last 30 seconds, a decrementing counter is displayed on screen.
It only appears in Kiosk mode. There should be no visible impact to the default ("embedded") mode.
https://doradotdev-staging--pr570-drafts-on-qckob4ep.web.app/quickcheck/kiosk/

Add countdown auto-restart function to Quick Check kiosk mode

---

firebase.json
test/redirects/redirects.csv

This PR adds a redirect from path `/next24` to `https://google.qualtrics.com/jfe/form/SV_8uCHA4aRzcGDjg2?source=next24?Q_lang=EN`
Preview at https://staging.dora.dev/next24

add redirect for next24

---

hugo/content/quickcheck/kiosk/_index.md

In kiosk mode, the `site-banner` element obscures the content. add CSS to suppress it.

suppress site banner in quick check kiosk mode

---

firebase.json
hugo/content/devops-capabilities/_index.md
hugo/content/devops-capabilities/cultural/transformational-leadership/index.md
hugo/content/devops-capabilities/process/visual-management/index.md
hugo/content/devops-capabilities/technical/cloud-infrastructure/index.md

The "how to transform" article has been moved out of Capabilities, into Guides. This PR updates the intra-site links.
Preview at https://doradotdev-staging--pr577-drafts-on-28lelabr.web.app/devops-capabilities/ (see link in header text)
Redirect from old link (was `302`, now `301`): https://staging.dora.dev/devops-capabilities/cultural/devops-culture-transform/

Update links to "how to transform" Guide

---

firebase.json
test/redirects/test-redirects.js

This redirect isn't working and is not essential. Remove it in the name of tidiness.

Remove "research archives" / tab redirect

---

hugo/assets/scss/guides.scss
hugo/content/sponsors/index.md
hugo/themes/dora/assets/scss/main.scss

This PR adds a page at `/sponsors` containing information for organizations about sponsoring the 2024 State of DevOps Report.
It also promotes the fix for #563 to apply to all pages.
Preview at https://doradotdev-staging--pr584-drafts-on-yq38sfij.web.app/sponsors/
Fixes #583

Add `/sponsors` page

---

test/redirects/redirects.csv

`/sponsor` redirects to `/sponsors/`, not `/sponsors`

Add a trailing `/` to fix a failing test

---

hugo/content/search/_index.md

This PR updates the `/search` page to reference the new [search.dora.dev](https://github.com/dora-team/search.dora.dev) service.
The page is only visible when hugo's `--buildDrafts` flag is passed. (So it's not visible on prod.)
preview at
https://doradotdev-staging--pr599-drafts-on-4anxawsx.web.app/search/

update search page to use search.dora.dev

---

hugo/layouts/research/section.html

Core V2 is available for public feedback. Let's link to it from dora.dev
Preview:
https://doradotdev-staging--pr600-drafts-on-10ivnz9c.web.app/research/

add core 2 preview link

---

hugo/themes/dora/assets/scss/main.scss
svelte/quick-check-2023/src/lib/MetricsQuestion.svelte

Brings equal gutters on smaller devices.
Hopefully improves things for #534

Uniform gutters on the quick check page

---

hugo/content/resources/_index.md
hugo/themes/dora/assets/scss/main.scss

On the resources page, use github logos instead of writing out "source repository"
Preview:  https://doradotdev-staging--pr620-drafts-off-zsjj9otu.web.app//resources/

Use github icons for the source repos

---

hugo/content/research/2023/dora-report/index.md
test/playwright/tests/2023-report.spec.ts

* Add links to download the report in the 9 available languages
* Add playwright tests for the 2023 report page
Fixes #622
Preview:  https://doradotdev-staging--pr623-drafts-off-esz59fls.web.app/research/2023/dora-report/

Add language options for 2023 report

---

hugo/config.toml
hugo/content/misc/code.md
hugo/themes/dora/assets/scss/main.scss
hugo/themes/dora/assets/scss/syntax-dora.scss
hugo/themes/dora/assets/scss/syntax.scss

This PR creates a stylesheet for use with code blocks. Within a markdown file, code blocks are created using standard syntax (surround code with three backticks, and an optional language specifier).
Preview at:
https://doradotdev-staging--pr630-drafts-on-8gyd2auv.web.app/misc/code/
Fixes #629

Add support for code blocks  (Fixes #629)

---

hugo/content/devops-capabilities/process/team-experimentation/index.md
hugo/content/devops-capabilities/technical/code-maintainability/index.md
hugo/content/devops-capabilities/technical/continuous-delivery/index.md
hugo/content/devops-capabilities/technical/test-data-management/index.md

This updates the capabilities articles that link to https://cloud.google.com/devops so that they now link to the DORA home page.
Preview links:
* https://doradotdev-staging--pr631-drafts-off-e6bvwntd.web.app/devops-capabilities/process/team-experimentation/#how-to-implement-team-experimentation
* https://doradotdev-staging--pr631-drafts-off-e6bvwntd.web.app/devops-capabilities/technical/code-maintainability/
* https://doradotdev-staging--pr631-drafts-off-e6bvwntd.web.app/devops-capabilities/technical/continuous-delivery/
* https://doradotdev-staging--pr631-drafts-off-e6bvwntd.web.app/devops-capabilities/technical/test-data-management/#how-to-implement-test-data-management

DORA links should link to dora.dev

---

hugo/themes/dora/layouts/partials/footer.html

This PR changes a `<div>` element in the footer to `<nav>` -- visually, there's no change, but the semantic `nav` element is preferable for accessibility, and I'm hopeful that it might help with the problem of navigation elements sneaking into search results (see below). _Caveat:_ if it _does_ help that problem, it won't help until the search crawler has had a chance to re-index the site and IDK when that will happen. So let's make this change, and then wait and hope. 😄 
Fixes #640

Add a <nav> element to the footer  (Fixes #640)

---

svelte/quick-check-2023/src/lib/Capability.svelte
svelte/quick-check-2023/src/lib/data/capability_prioritization_questions.json

This PR updates the headings on the "help me prioritize" questions - it switches the culture questions to start with "in my organization..." and removes the heading from the LCA questions because those contain their own contexts.
Preview: https://doradotdev-staging--pr642-drafts-on-godc4w1m.web.app/quickcheck/?leadtime=2&deployfreq=5&changefailure=30&failurerecovery=2&v=2023&industry=all#whats-holding-you-back
Fixes #627

Improve language on prioritization exercise (Fixes #627)

---

hugo/content/guides/_index.md

This trivial fix updates the banner subtitle on the DORA guides page to spell "practitioners" correctly instead of the misspelled "practioners".
Preview:  https://doradotdev-staging--pr653-drafts-off-nn5oxgyl.web.app/guides

bug(guides): Update banner subtitle to use "practitioners"

---

hugo/content/research/2024/_index.md
hugo/content/survey/_index.md
hugo/layouts/partials/site_banner.html
test/playwright/tests/2024-research.spec.ts
test/playwright/tests/survey.spec.ts

This commit updates the 2024 DORA survey page to reflect that the survey is now closed.
The following changes were made:
* Removed the survey banner from the site.
* Removed the survey call to action from the 2024 research page.
* Updated the 2024 research page to indicate that the survey is closed and thank participants.
* Updated the survey page to indicate that the survey is closed and thank participants.
This also adds a banner to apply for the Google Cloud DORA Awards
Preview:
* https://doradotdev-staging--pr668-drafts-off-knf90j9n.web.app/research/2024/
* https://doradotdev-staging--pr668-drafts-off-knf90j9n.web.app/survey/

Update 2024 DORA survey page

---

svelte/core-v2/src/lib/Popover.svelte
svelte/core-v2/src/lib/core_data.json

This PR updates the Core popovers for Software Delivery and each of the four key metrics, adding a link to the quickcheck.
It also applies a subtle border to the "learn more" link to separate it from links in the popover content.
Preview: https://doradotdev-staging--pr685-drafts-on-1mi744e0.web.app/research/
Fixes #682

Link to quick check from software delivery performance in core model  (Fixes #682)

---

hugo/content/research/2024/_index.md
hugo/content/survey/_index.md

This commit updates the 2024 DORA survey and research pages to reflect that the report is expected to be published in October 2024.
The change ensures that users are informed about the expected publication date and can join the DORA community to stay updated.
Preview:
* [2024 research](https://doradotdev-staging--pr688-drafts-off-utvfbym1.web.app/research/2024/)
* [survey](https://doradotdev-staging--pr688-drafts-off-utvfbym1.web.app/survey)

Update survey and research pages to reflect report publication date

---

hugo/content/publications/_index.md
test/playwright/tests/publications/index.spec.ts

* Update the test for the publications landing page
* Link the ROI Report to the landing page
Preview:  https://doradotdev-staging--pr701-drafts-on-2v5jh3xr.web.app/publications/
Fixes #700

Link the ROI report under `/publications` to the ROI landing page.

---

test/playwright/tests/search/search-page.spec.ts

ask.dora.dev sometimes appears in the search results. This adds and explicit test for it in the sidebar.
Also refactors to match our emerging playwright conventions.

Refactor playwright tests for `/search/`

---

ci/firebase-config.doradotdev-staging.js
ci/firebase-config.doradotdev.js
ci/preview-content.cloudbuild.yaml
docs/README.md

This PR strips out Firebase config files and CI infra that is no longer necessary, since we've replaced the Firebase-powered contact form.
Fixes #746
Fixes #747
Fixes #748

remove firebase config

---

hugo/content/guides/dora-metrics-four-keys/index.md

Stability measures stability, not throughput.
Preview: https://doradotdev--pr755-drafts-off-zq7n07fs.web.app/guides/dora-metrics-four-keys/#:~:text=DORA%20assesses%20stability

Fixes a typo in the Four Keys guide

---

test/playwright/tests/capabilities/job-satisfaction.spec.ts

There was an intermittent failure locally. This seems to have resolved that while also improving the maintainability of the test.

Refactor tests for job satisfaction

---

hugo/content/_index.md
test/playwright/tests/homepage.spec.ts

The AI Preview image is giving a 404.
This fixes the path and adds additional tests for the home page.
This bug was introduced in 9b006fda123563d6625151866bc654f25d21f43a.
Fixes #762 
Preview - https://doradotdev--pr761-drafts-off-gywayge1.web.app/

Fix broken image on the home page

---

hugo/content/research/2018/dora-report/index.md

Fixes a broken link to the 2018 report.

---

hugo/content/research/2024/questions.md
hugo/layouts/research_archives/questions/single.html
test/playwright/tests/research/2024/2024-questions.spec.ts

* Adds placeholder for 2024 questions.
* Adds a `.` at the end of the sentence
* Removes some trailing whitespace
Preview links:
* https://doradotdev--pr776-drafts-off-ueevmz8m.web.app/research/2024/questions/
* https://doradotdev--pr776-drafts-off-ueevmz8m.web.app/research/2023/questions/ (look for the `.`)

2024 survey questions

---

hugo/content/research/2024/errata.md

Currently in `draft`
Need to verify the version in the final report.
Preview: https://doradotdev--pr781-drafts-on-2y04av8j.web.app/research/2024/errata
With drafts off, a 404 is expected at https://doradotdev--pr781-drafts-off-burwjgey.web.app/research/2024/errata
Supports: #689

Prep the 2024 errata page

---

test/redirects/redirects.csv

No functionality changes, just removes an extra `,` from `redirects.csv`

Fix typo in redirects to be tested

---

hugo/content/research/2024/dora-report/index.md

They're a gold sponsor for the 2024 report and have requested a new URL.
Preview:
* https://doradotdev--pr805-drafts-off-uzzclqh6.web.app/research/2024/dora-report/
The midelware logo should link to:
https://www.middlewarehq.com/middleware-open-source?utm_source=dora_report
not to
https://middlewarehq.com/ which is where it is currently linking on https://dora.dev/research/2024/dora-report/

Update middleware link

---

hugo/themes/dora/layouts/partials/footer.html

This commit updates the social media links in the footer to point to the correct DORA accounts.
The previous links pointed to outdated accounts for "DevOps Research & Assessment", which is no longer the correct branding. The new links point to the correct accounts for "DORA".
Preview: https://doradotdev--pr810-drafts-off-z9q6rws6.web.app/
The Twitter and LinkedIn links should got to doradotdev.

fix: Update social media links in footer

---

firebase.json
hugo/content/_index.md
hugo/content/guides/how-to-innovate-with-generative-ai/index.md
hugo/content/publications/_index.md
hugo/content/quickcheck/2019/results.html
hugo/content/research/2023/structural-equation-models/index.md
hugo/content/research/2024/dora-report/index.md
hugo/layouts/partials/quickcheck/percentile_graph.html
hugo/layouts/partials/quickcheck/performance_comparison.html
hugo/themes/dora/layouts/partials/site_banner.html
test/playwright/tests/publications/index.spec.ts
test/redirects/redirects.csv

Fixes #801 and fixes #821 
Previous links to the latest 2024 DORA report pointed to `https://cloud.google.com/resources/devops/state-of-devops`. This PR removes the `/resources` from the URL.
Additionally, build errors were present when running `hugo` command. Changes to the dates within two index.md files addresses these errors.

Removing /resources from State of DevOps report link as well as fixing hugo build issues

---

hugo/content/guides/value-stream-management/index.md

To help readers digest the guide the [dora.commury](https://dora.community) discussion about the VSM DORA guide that's on   [YouTube](https://www.youtube.com/watch?v=HBEtKSIznn0) has been added to the [VSM guide](https://dora.dev/guides/value-stream-management/). 
The `last updated` filed has been updated.

Added the community recording discussing VSM guide

---

hugo/content/vc/_index.md

This makes it more obvious in the version checker whether or not you have the most recent version.
Fixes #831 
Preview links:
* https://doradotdev--pr832-drafts-off-au5s23yw.web.app/vc/
* https://doradotdev--pr832-drafts-off-au5s23yw.web.app/vc/?v=2024.3
* https://doradotdev--pr832-drafts-off-au5s23yw.web.app/vc/?v=2024.2
* https://doradotdev--pr832-drafts-off-au5s23yw.web.app/vc/?v=2024.1
* https://doradotdev--pr832-drafts-off-au5s23yw.web.app/vc/?v=2023-12
* https://doradotdev--pr832-drafts-off-au5s23yw.web.app/vc/?v=2023-10
* https://doradotdev--pr832-drafts-off-au5s23yw.web.app/vc/?v=
* https://doradotdev--pr832-drafts-off-au5s23yw.web.app/vc/?v=216
* https://doradotdev--pr832-drafts-off-au5s23yw.web.app/vc/?v=1564-1586
* https://doradotdev--pr832-drafts-off-au5s23yw.web.app/vc/?foo=15 …

Clarify the status of the version being checked

---

hugo/content/vc/_index.md
test/playwright/tests/vc/version-check.spec.ts

We are printing the report and the printed version will have a new version number: v. 2024.3.p.
This updates the version checker page and related tests to account for this.
Preview URLs:
• https://doradotdev--pr844-drafts-off-40cifagj.web.app//vc/
• https://doradotdev--pr844-drafts-off-40cifagj.web.app//vc/?v=2024.3.p
• https://doradotdev--pr844-drafts-off-40cifagj.web.app//vc/?v=2024.3
• https://doradotdev--pr844-drafts-off-40cifagj.web.app//vc/?v=2024.2
• https://doradotdev--pr844-drafts-off-40cifagj.web.app//vc/?v=2024.1
• https://doradotdev--pr844-drafts-off-40cifagj.web.app//vc/?v=2023-12
• https://doradotdev--pr844-drafts-off-40cifagj.web.app//vc/?v=2023-10
• https://doradotdev--pr844-drafts-off-40cifagj.web.app//vc/?v=
• https://doradotdev--pr844-drafts-off-40cifagj.web.app//vc/?v=2 …

Add support for printed version check

---

hugo/content/guides/devops-culture-transform/index.md

The How to transform your organization guide references Appendix B of the 2019 report. This adds a link to that page.
Preview: 
https://doradotdev--pr860-drafts-off-ron7chmy.web.app/guides/devops-culture-transform/#build-community-structures-to-spread-knowledge  - look for the link in "see Appendix B of the 2019 State of DevOps Report for detailed descriptions"

Link to the 2019 report

---

hugo/content/research/ai/adopt-gen-ai/index.md

This allows space for the "click to copy" functionality
Preview:https://doradotdev--pr870-drafts-off-us9x2wlf.web.app/research/ai/adopt-gen-ai/#alleviate-anxieties-about-ai-related-job-displacement
Heading "Alleviate anxieties about AI-related job displacement" should appear on one line along with the "click to copy" link.

AI adoption - change sub-headers from h2 to h3

---

hugo/content/research/2024/questions.md
hugo/layouts/research_archives/questions/single.html
test/playwright/tests/research/2024/2024-questions.spec.ts

The report was published in October of 2024.
Preview: https://doradotdev--pr871-drafts-off-8u71n48d.web.app/research/2024/questions/
Should say
"Responses to the following questions were used in the analysis published in the [2024 Accelerate State of DevOps Report](https://doradotdev--pr871-drafts-off-8u71n48d.web.app/research/2024/dora-report/)."
Production currently says:
Responses to the following questions were used in the analysis published in the 2024 Accelerate State of DevOps Report (coming soon).

Remove the "(coming soon)" from the 2024 questions

---

hugo/content/research/ai/_index.md

Preview - https://doradotdev--pr875-drafts-off-yozy2e3m.web.app/research/ai/#ai-research
The link to [Fostering developers’ trust in generative artificial intelligence](https://dora.dev/research/ai/trust-in-ai./) should work.

Fix broken link on AI research page

---

hugo/content/research/ai/adopt-gen-ai/index.md
hugo/content/research/ai/questions.md
hugo/content/research/core/questions.md
hugo/data/survey_questions/ai-adoption.json
hugo/layouts/research_archives/questions/single.html
test/playwright/tests/research/ai/ai-adoption-questions.spec.ts
test/playwright/tests/research/core/core-questions.spec.ts

* Add the questions used for researching AI adoption
* Update the AI adoption article to link to the questions
* Changes to the layout of questions (impacts annual research and core questions)
* Adds new frontmatter parameter: `research_collection_title` used by core and AI adoption questions.
* Adds and updates tests
Preview links
* https://doradotdev--pr873-drafts-off-hyx2vneq.web.app/research/ai/adopt-gen-ai/#notes-on-method
* https://doradotdev--pr873-drafts-off-hyx2vneq.web.app/research/ai/questions/
* https://doradotdev--pr873-drafts-off-hyx2vneq.web.app/research/core/questions/

Add questions used in the AI adoption research

---

firebase.json

Prevents the default redirect from triggering.

Adds another redirect for devops-culture-transform

---

hugo/content/search/search.js

This adds some logic for PDF titles on the search results page.
* Before 2018 - State of DevOps Report
* 2018 and later - Accelerate State of DevOps Report 
* 2020 - ROI of DevOps Transformation
This supports https://github.com/dora-team/search.dora.dev/issues/16 and https://github.com/dora-team/search.dora.dev/issues/17
Preview URL - https://doradotdev--pr886-drafts-off-xh0hd3qc.web.app/search/?q=roi
Comparison URL - https://dora.dev/search/?q=roi
This search result should show all three title sytles.

Better handling of PDF titles in search index.

---

hugo/content/sponsors/resource-center/index.md

The sponsor resource center now links to the branding guidelines instead of providing a .zip of outdated logos.
Preview - https://doradotdev--pr889-drafts-off-zme6quuj.web.app/sponsors/resource-center/

Update DORA Logo links

---

hugo/content/capabilities/documentation-quality/index.md
test/playwright/tests/capabilities/documentation-quality.spec.ts
test/redirects/README.md

* Fix a link to the 2022 questions
* Fix a link to the 2022 SEM
* Fix a link to the 2021 report
* Refactors the playwright tests for the page
* Removes a TODO from the redirect tests
Preview - https://doradotdev--pr893-drafts-off-5cqsl6y7.web.app/capabilities/documentation-quality/

Updates to the documentation quality article

---

.gemini/README.md
.gemini/config.yaml
.gemini/styleguide.md

This PR adds DORA-specific configuration for Gemini Code Assist reviews (provided by the bot on GitHub). Info about the config options can be found at https://developers.google.com/gemini-code-assist/docs/customize-gemini-behavior-github
Notes:
- I have found the "summaries" (which are posted before the review takes place) to be un-useful, so I disabled that feature
- I copied the "styleguide" from @sapientcoffee; thanks Rob!
/cc @nathenharvey

add config for gemini reviews

---

test/playwright/tests/research/2024/2024-navigation.spec.ts

As far as I can tell/remember, the only remaining place where Alpine is used is in the `tab_navigation` partial. _And_ the `tab_navigation` partial is actually not used any more (it was last used on the legacy quick check which has now been removed -- see #911). The research pages have a newer/simpler tab implementation which doesn't use JS. (it's in `partials/research_archives_tabs.html`)
So adding this test isn't _actually_ related to Alpine, but it does relate to functionality that Alpine once provided, and it's a good check to have.

UI tests for alpine mechanisms  (Fixes #729)

---

hugo/content/vc/genai/index.md
test/playwright/tests/vc/genai-version-check.spec.ts
test/playwright/tests/vc/version-check.spec.ts

* Updates the gen AI report version checker
* Adds tests to the version checker for the gen AI report
* Updates a test for the DORA Report version checker to check the expected text, previously only the version number was being validated.
Preview URLs:
* https://doradotdev--pr923-drafts-off-i6d4sqv1.web.app/vc/genai/
* https://doradotdev--pr923-drafts-off-i6d4sqv1.web.app/vc/genai/?v=2025.1.p

Add version checker for printed gen AI reports

---

hugo/content/research/ai/errata.md

"acquire" should not be split across lines.
Preview: https://doradotdev--pr951-drafts-off-5q1pvq0p.web.app/research/ai/errata/

One errata for the gen ai report

---

hugo/content/research/ai/errata.md
hugo/content/vc/genai/index.md
test/playwright/tests/vc/genai-version-check.spec.ts

* Update errata page
* Update version checker
* Update tests
Preview URLs:
* Unrecognized - https://doradotdev--pr955-drafts-off-0k5i7hp2.web.app//vc/genai/?v=2025.13
* Latest - https://doradotdev--pr955-drafts-off-0k5i7hp2.web.app//vc/genai/?v=2025.2
* Outdated - https://doradotdev--pr955-drafts-off-0k5i7hp2.web.app//vc/genai/?v=2025.1
* Print - https://doradotdev--pr955-drafts-off-0k5i7hp2.web.app//vc/genai/?v=2025.2.p

v. 2025.2 of the gen ai report is available

---

hugo/content/research/ai/errata.md

This error exists in both versions of the report.
Preview: https://doradotdev--pr961-drafts-off-dhryouzf.web.app/research/ai/errata/

Another errata in the Gen AI report

---

svelte/core-v2/index.html
svelte/core-v2/src/app.css

This PR changes the way fonts are handled in the svelte code for Core, so that the Core elements will inherit fonts from the Hugo theme rather than specifying their own. (When developing, the svelte app does have its own font styles, but these are not copied into the Hugo content when the build script is run.)
For the `dora` theme, Core inherits that theme's "Google Sans [classic]" font; for `dora-2025`, it inherits the newer "Google Sans Flex". They don't really look any different, but they have slightly different optical rendering, and that's what was causing the problem reported in #963.
Fix #963

Fix style corruption due to Core 

---

hugo/themes/dora-2025/assets/scss/footer.scss
hugo/themes/dora-2025/assets/scss/forms.scss
hugo/themes/dora-2025/assets/scss/guides.scss
hugo/themes/dora-2025/assets/scss/headings.scss
hugo/themes/dora-2025/assets/scss/homepage.scss
hugo/themes/dora-2025/assets/scss/main.scss
hugo/themes/dora-2025/assets/scss/nav.scss
hugo/themes/dora-2025/assets/scss/normalize.scss
hugo/themes/dora-2025/assets/scss/search-input.scss
hugo/themes/dora-2025/layouts/partials/header.html

This PR adds responsive/mobile styles, with a focus on portrait-mode phone screen sizes. _Tablets and landscapes work too; it's fully responsive, but some of those might not be quite as elegant; per Google analytics, our traffic is 87.3% desktop, 12.2% mobile, and 0.2% tablet [most of which is probably me; I'm an iPad guy])._
It also uses a simplified implementation of the mobile menu. IMHO, it looks better, and it will be more maintainable. I removed the slinky animation that transforms the hamburger menu into an X and back, but that was always kind of gimmicky.
There should be no effect on prod (or in the preview); here's what it looks like (with mobile emulation) on my local:
Fixes #965 
Fixes #964  
Fixes #973

Mobile and misc styles for dora-2025

---

hugo/themes/dora-2025/assets/scss/research.scss

This PR removes padding from `main` to allow room for the Core model (this was a regression due to the switch from `dora` theme to `dora-2025`).
Preview: https://doradotdev--pr986-drafts-on-8xmihi1u.web.app/research/?view=detail
Fixes #984
(Note that this still doesn't solve for narrow viewports; we still need to do something for #683)

Allow wider page for Core diagram

---

hugo/content/capabilities/continuous-integration/index.md

Well, the second to the last as it's also on the press release announcing the acquisition by Google Cloud but it's appropriate to keep that one.
Preview: https://doradotdev--pr989-drafts-off-f8hsoyjj.web.app/capabilities/continuous-integration/

Remove last instance of expanded DORA acronym

---

hugo/content/brand-guidelines/_index.md
hugo/content/sponsors/resource-center/index.md
test/playwright/tests/brand-guidelines/dora-brand-guidelines.spec.ts

* Updates the sponsor resource center for 2025
* Adds the graphics for the Gen AI report to the brand guidelines page
* Notes that DORA is no longer an acronym on the brand guidelines page
Preview URLs:
* https://doradotdev--pr991-drafts-off-ptlcvie4.web.app/sponsors/resource-center/
* https://doradotdev--pr991-drafts-off-ptlcvie4.web.app/brand-guidelines/

Update sponsor resource center and brand guidelines for 2025

---

test/playwright/tests/capabilities/well-being.spec.ts

This change only adds a new test. If the preview site builds, the tests have passed.
Preview: https://doradotdev--pr996-drafts-off-gkf83k7p.web.app/

Add a test for the well-being page.

---

hugo/content/brand-guidelines/_index.md

Trivial change that updates the size of the zip file.
Preview URL: https://doradotdev--pr1007-drafts-off-8sxlyy1n.web.app/brand-guidelines/
Should show the DORA Survey Logos file is `1.1MB` which should match the file size if you download it.

Add more 2025 survey logos

---

hugo/content/survey/discussion-guide/index.md

Preview: https://doradotdev--pr1014-drafts-off-2lzimdfj.web.app/survey/discussion-guide/ now includes a link to https://conversations.dora.dev/survey.
Look for it in [this section](https://doradotdev--pr1014-drafts-off-2lzimdfj.web.app/survey/discussion-guide/#suggested-discussion-questions-40-minutes).

Link the survey discussion guide to conversations.dora.dev

---

hugo/content/capabilities/version-control/index.md
test/playwright/tests/capabilities/version-control.spec.ts

Updates the Version Control capability article:
* Add updated date
* Style change, '*' for bullets
* Fix a typo
* Add links to three Google Cloud products
* [Google Cloud Artifact Registry](https://cloud.google.com/artifact-registry/)
* [Google Cloud Storage](https://cloud.google.com/storage)
* [Infrastructure Manager](https://cloud.google.com/infrastructure-manager/)
* Add "More from DORA"
* Update "What's Next"
Adds a test for the version control page.
Preview URL: https://doradotdev--pr1040-drafts-off-mb3yinsy.web.app/capabilities/version-control/

Update the version control capability

---

test/redirects/test-redirects.js

The local Firebase emulator appends a trailing ampersand to redirected URLs that contain query strings. This change modifies the redirect test to account for this behavior by removing the trailing ampersand before asserting the redirect location.

feat: Handle trailing ampersand in redirects

---

hugo/content/contact/_index.md
hugo/content/publications/errata.md
hugo/content/research/2025/errata.md
test/playwright/tests/contact.spec.ts
test/playwright/tests/research/2025/2025-errata.spec.ts

Adds a new errata section for the 2025 DORA report.
This includes:
- A new page at /research/2025/errata/ to display errata.
- An updated contact form to allow users to submit errata for the 2025 report.
- New and updated Playwright tests to cover the new functionality.
Fixes #1049
Preview URLs:
* https://doradotdev--pr1094-drafts-off-xc5dwat9.web.app/publications/errata/
* https://doradotdev--pr1094-drafts-off-xc5dwat9.web.app/research/2025/errata/

feat(2025-report): Add errata section

---

hugo/content/vc/_index.md
test/playwright/tests/vc/version-check.spec.ts

* Refactors the playwright tests for the version checker
* Adds version checker for version `2025.1`
* Adds link to all publications for all versions not in the latest year (2025)
Fixes #1057 
Preview URLs:
* https://doradotdev--pr1087-drafts-off-khyb7ij9.web.app/vc/
* https://doradotdev--pr1087-drafts-off-khyb7ij9.web.app/vc/?v=2025.1

Version checker updates for 2025.1
